version: "3"

services:
  frontend:
#    image: okta-test
    container_name: "okta-test"
    build: .
    ports:
      - '80:8000'
    volumes:
      - ./src:/app/src:ro
      - ./public://app/public:ro
    networks:
      - webnet
networks:
  webnet:
